version: '3.3'

services: 
    wordpress:
        image: wordpress:latest
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ODUser
            WORDPRESS_DB_PASSWORD: ODPass
            WORDPRESS_DB_NAME: ODDb
        volumes: 
            # - ./wordpress:/var/www/html
            - ./wordpress/:/var/www/html
            # - ./src:/var/www/html/wp-content/plugins/meu-plugin

    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: ODDb
            MYSQL_USER: ODUser
            MYSQL_PASSWORD: ODPass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql

    # adminer:
    #     depends_on: 
    #         - db
    #     image: adminer
    #     restart: always
    #     ports: 
    #         - 8888:8080

# networks: 
#     back:
        
volumes: 
    db: